// <auto-generated />
using System;
using APIMiddleware.Core.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIMiddleware.Core.Migrations
{
    [DbContext(typeof(APIMiddlewareContext))]
    partial class APIMiddlewareContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIMiddleware.Core.DBContext.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PROJECT_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CREATED_BY")
                        .HasColumnName("CREATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CREATION_DATE")
                        .HasColumnName("CREATION_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("LAST_UPDATED_BY")
                        .HasColumnName("LAST_UPDATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LAST_UPDATE_DATE")
                        .HasColumnName("LAST_UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProjectId")
                        .HasColumnName("PROJECT_CODE")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasColumnName("PROJECT_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowVersion")
                        .HasColumnName("ROW_VERSION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("MID_PROJECTS");
                });

            modelBuilder.Entity("APIMiddleware.Core.DBContext.Entities.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("REQUEST_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Created_By")
                        .HasColumnName("CREATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Creation_Date")
                        .HasColumnName("CREATION_DATE")
                        .HasColumnType("datetime2");

                    b.Property<long>("ElapsedMilliseconds")
                        .HasColumnName("ELAPSED_TIME")
                        .HasColumnType("bigint");

                    b.Property<string>("IP_Address")
                        .HasColumnName("IP_ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Last_Update_Date")
                        .HasColumnName("LAST_UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("Last_Updated_By")
                        .HasColumnName("LAST_UPDATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnName("PROJECT_ID")
                        .HasColumnType("int");

                    b.Property<string>("QueryString")
                        .HasColumnName("QUERY_STRING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RequestBody")
                        .HasColumnName("REQUEST_BODY")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RequestFormat")
                        .HasColumnName("REQUEST_FORMAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestFunction")
                        .HasColumnName("REQUEST_FUNCTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestGuid")
                        .HasColumnName("REQUEST_GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMethod")
                        .HasColumnName("REQUEST_METHOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestStatus")
                        .HasColumnName("REQUEST_STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnName("REQUEST_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestUrl")
                        .HasColumnName("REQUEST_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ResponseBody")
                        .HasColumnName("RESPONSE_BODY")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ResponseCode")
                        .HasColumnName("RESPONSE_CODE")
                        .HasColumnType("int");

                    b.Property<string>("ResponseFormat")
                        .HasColumnName("RESPONSE_FORMAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowVersion")
                        .HasColumnName("ROW_VERSION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnName("USER_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("ProjectId");

                    b.ToTable("MID_REQUESTS");
                });

            modelBuilder.Entity("APIMiddleware.Core.DBContext.Entities.SystemPreference", b =>
                {
                    b.Property<int>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PreferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferenceValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PreferenceId");

                    b.ToTable("SystemPreferences");
                });

            modelBuilder.Entity("APIMiddleware.Core.DBContext.Entities.Request", b =>
                {
                    b.HasOne("APIMiddleware.Core.DBContext.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
