//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageQuereyProductionService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dtts.sfda.gov.sa/PackageQueryService")]
    public partial class faultBean
    {
        
        private string fcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FC
        {
            get
            {
                return this.fcField;
            }
            set
            {
                this.fcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dtts.sfda.gov.sa/PackageQueryService")]
    public partial class transferDetail
    {
        
        private string fROMGLNField;
        
        private string tOGLNField;
        
        private long tRANSFERIDField;
        
        private System.DateTime sENDDATEField;
        
        private bool sENDDATEFieldSpecified;
        
        private System.DateTime fIRSTTRANSFERDATEField;
        
        private bool fIRSTTRANSFERDATEFieldSpecified;
        
        private System.DateTime lASTTRANSFERDATEField;
        
        private bool lASTTRANSFERDATEFieldSpecified;
        
        private string mD5CHECKSUMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FROMGLN
        {
            get
            {
                return this.fROMGLNField;
            }
            set
            {
                this.fROMGLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TOGLN
        {
            get
            {
                return this.tOGLNField;
            }
            set
            {
                this.tOGLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long TRANSFERID
        {
            get
            {
                return this.tRANSFERIDField;
            }
            set
            {
                this.tRANSFERIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime SENDDATE
        {
            get
            {
                return this.sENDDATEField;
            }
            set
            {
                this.sENDDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SENDDATESpecified
        {
            get
            {
                return this.sENDDATEFieldSpecified;
            }
            set
            {
                this.sENDDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=4)]
        public System.DateTime FIRSTTRANSFERDATE
        {
            get
            {
                return this.fIRSTTRANSFERDATEField;
            }
            set
            {
                this.fIRSTTRANSFERDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FIRSTTRANSFERDATESpecified
        {
            get
            {
                return this.fIRSTTRANSFERDATEFieldSpecified;
            }
            set
            {
                this.fIRSTTRANSFERDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=5)]
        public System.DateTime LASTTRANSFERDATE
        {
            get
            {
                return this.lASTTRANSFERDATEField;
            }
            set
            {
                this.lASTTRANSFERDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LASTTRANSFERDATESpecified
        {
            get
            {
                return this.lASTTRANSFERDATEFieldSpecified;
            }
            set
            {
                this.lASTTRANSFERDATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MD5CHECKSUM
        {
            get
            {
                return this.mD5CHECKSUMField;
            }
            set
            {
                this.mD5CHECKSUMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dtts.sfda.gov.sa/PackageQueryService")]
    public partial class packageQueryServiceResponse
    {
        
        private transferDetail[] tRANSFERDETAILLISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TRANSFERDETAIL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public transferDetail[] TRANSFERDETAILLIST
        {
            get
            {
                return this.tRANSFERDETAILLISTField;
            }
            set
            {
                this.tRANSFERDETAILLISTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dtts.sfda.gov.sa/PackageQueryService")]
    public partial class packageQueryServiceRequest
    {
        
        private string fROMGLNField;
        
        private string tOGLNField;
        
        private bool gETALLField;
        
        private System.DateTime sTARTDATEField;
        
        private System.DateTime eNDDATEField;
        
        public packageQueryServiceRequest()
        {
            this.gETALLField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FROMGLN
        {
            get
            {
                return this.fROMGLNField;
            }
            set
            {
                this.fROMGLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TOGLN
        {
            get
            {
                return this.tOGLNField;
            }
            set
            {
                this.tOGLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool GETALL
        {
            get
            {
                return this.gETALLField;
            }
            set
            {
                this.gETALLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime STARTDATE
        {
            get
            {
                return this.sTARTDATEField;
            }
            set
            {
                this.sTARTDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=4)]
        public System.DateTime ENDDATE
        {
            get
            {
                return this.eNDDATEField;
            }
            set
            {
                this.eNDDATEField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dtts.sfda.gov.sa/PackageQueryService", ConfigurationName="PackageQuereyProductionService.PackageQueryService")]
    public interface PackageQueryService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dtts.sfda.gov.sa/PackageQueryService/PackageQueryService/packageQueryReque" +
            "st", ReplyAction="http://dtts.sfda.gov.sa/PackageQueryService/PackageQueryService/packageQueryRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PackageQuereyProductionService.faultBean), Action="http://dtts.sfda.gov.sa/PackageQueryService/PackageQueryService/packageQuery/Faul" +
            "t/ServiceError", Name="ServiceError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PackageQuereyProductionService.packageQueryResponse packageQuery(PackageQuereyProductionService.packageQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dtts.sfda.gov.sa/PackageQueryService/PackageQueryService/packageQueryReque" +
            "st", ReplyAction="http://dtts.sfda.gov.sa/PackageQueryService/PackageQueryService/packageQueryRespo" +
            "nse")]
        System.Threading.Tasks.Task<PackageQuereyProductionService.packageQueryResponse> packageQueryAsync(PackageQuereyProductionService.packageQueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class packageQueryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dtts.sfda.gov.sa/PackageQueryService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PackageQuereyProductionService.packageQueryServiceRequest PackageQueryServiceRequest;
        
        public packageQueryRequest()
        {
        }
        
        public packageQueryRequest(PackageQuereyProductionService.packageQueryServiceRequest PackageQueryServiceRequest)
        {
            this.PackageQueryServiceRequest = PackageQueryServiceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class packageQueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dtts.sfda.gov.sa/PackageQueryService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PackageQuereyProductionService.packageQueryServiceResponse PackageQueryServiceResponse;
        
        public packageQueryResponse()
        {
        }
        
        public packageQueryResponse(PackageQuereyProductionService.packageQueryServiceResponse PackageQueryServiceResponse)
        {
            this.PackageQueryServiceResponse = PackageQueryServiceResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface PackageQueryServiceChannel : PackageQuereyProductionService.PackageQueryService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PackageQueryServiceClient : System.ServiceModel.ClientBase<PackageQuereyProductionService.PackageQueryService>, PackageQuereyProductionService.PackageQueryService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PackageQueryServiceClient() : 
                base(PackageQueryServiceClient.GetDefaultBinding(), PackageQueryServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PackageQueryService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PackageQueryServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PackageQueryServiceClient.GetBindingForEndpoint(endpointConfiguration), PackageQueryServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PackageQueryServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PackageQueryServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PackageQueryServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PackageQueryServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PackageQueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PackageQuereyProductionService.packageQueryResponse packageQuery(PackageQuereyProductionService.packageQueryRequest request)
        {
            return base.Channel.packageQuery(request);
        }
        
        public System.Threading.Tasks.Task<PackageQuereyProductionService.packageQueryResponse> packageQueryAsync(PackageQuereyProductionService.packageQueryRequest request)
        {
            return base.Channel.packageQueryAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PackageQueryService))
            {
                //System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                System.ServiceModel.BasicHttpsBinding result = new System.ServiceModel.BasicHttpsBinding(System.ServiceModel.BasicHttpsSecurityMode.Transport);
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                //result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PackageQueryService))
            {
                return new System.ServiceModel.EndpointAddress("https://rsd.sfda.gov.sa/ws/PackageQueryService/PackageQueryService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PackageQueryServiceClient.GetBindingForEndpoint(EndpointConfiguration.PackageQueryService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PackageQueryServiceClient.GetEndpointAddress(EndpointConfiguration.PackageQueryService);
        }
        
        public enum EndpointConfiguration
        {
            
            PackageQueryService,
        }
    }
}
